apiVersion: v1
kind: Service
metadata:
  name: deployment-cats-cats
  labels:
    course: clo835
    app: cats
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: cats-pod